name: 'Mojira Deploy'
description: 'Deploy Mojira community bots to the Mojira VPS'
inputs:
  vps_host:
    description: "The VPS host's IP address or domain name."
    required: true
  vps_user:
    description: "User name for authentication."
    required: false
    default: "mojira"
  vps_ssh_key:
    description: "Private SSH key to use for connecting."
    required: true
  vps_known_hosts:
    description: "Known Hosts file to use for connecting with SSH."
    required: true
  artifact_paths:
    description: "Paths to artifacts (folders or files) to upload. String with exactly one path per line, and an empty line at the end."
    required: true
  artifact_destination:
    description: "Target folder for artifact upload."
    required: true
  rsync_args:
    description: "Arguments for uploading artifacts via rsync."
    required: false
    default: -avhW --delete
  script:
    description: "Script to run after uploading of artifacts."
    required: false
    default: ""

runs:
  using: 'composite'
  steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.8.1
      with:
        key: ${{ inputs.vps_ssh_key }}
        known_hosts: ${{ inputs.vps_known_hosts }}
    - name: Upload Artifacts
      run: |
        while IFS= read -r ARTIFACT_PATH; do
          echo Uploading artifact $ARTIFACT_PATH...
          ARTIFACT_SLASH_PATH=/$ARTIFACT_PATH
          rsync $INPUT_RSYNC_ARGS $GITHUB_WORKSPACE/$ARTIFACT_PATH $INPUT_VPS_USER@$INPUT_VPS_HOST:$INPUT_ARTIFACT_DESTINATION${ARTIFACT_SLASH_PATH%/*}
        done < <(printf '%s' "$INPUT_ARTIFACT_PATHS")
      shell: bash
    - name: Run Deploy Script
      uses: appleboy/ssh-action@v1.2.5
      with:
        host: ${{ inputs.vps_host }}
        username: ${{ inputs.vps_user }}
        key: ${{ inputs.vps_ssh_key }}
        script: ${{ inputs.script }}

branding:
  color: "green"
  icon: "upload-cloud"
