name: 'Mojira Deploy'
description: 'Deploy Mojira community bots to the Mojira VPS'
inputs:
  project_folder:
    description: "Folder name for this project on the Mojira VPS."
    required: true
  artifact_paths:
    description: "Paths to artifacts (folders or files) to upload. String with exactly one path per line, and an empty line at the end."
    required: true
  artifact_destination:
    description: "Target folder for artifact upload."
    required: true
  rsync_args:
    description: "Arguments for uploading artifacts via rsync."
    required: false
    default: -avhW --delete
  script:
    description: "Script to run after uploading of artifacts."
    required: false
    default: ""

runs:
  using: 'composite'
  steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VPS_SSH_KEY }}
        known_hosts: ${{ secrets.VPS_KNOWN_HOSTS }}
    - name: Upload Artifacts
      run: |
        while IFS= read -r ARTIFACT_PATH; do
          echo Uploading artifact $ARTIFACT_PATH...
          rsync $RSYNC_ARGS $GITHUB_WORKSPACE/$ARTIFACT_PATH ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:$PROJECT_FOLDER/$ARTIFACT_DESTINATION
        done < <(printf '%s' "$ARTIFACT_PATHS")
    - name: Run Deploy Script
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: $SCRIPT

branding:
  color: "green"
  icon: "upload-cloud"
